project:
  type: website

website:
  title: "Comunicá tus datos con R y Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Taller
      - href: about.qmd
        text: "👋 Soy Jesica"
      - href: slides.qmd
        text: Diapositivas
  favicon: "img/logo-rladies-BA.png"

format:
  html:
    theme:
      - minty
      - brand

editor: visual

lang: es 
