project:
  type: website

website:
  title: "Comunicá tus datos con R y Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: slides.qmd
        text: Slides

format:
  html:
    theme:
      - minty
      - brand

editor: visual

lang: es 
